apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager-pprof-service
  namespace: system
spec:
  ports:
  - name: https
    port: 6061
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
