apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: application-api-binding
spec:
  reference:
    workspace:
      exportName: spi
      path: root:redhat-appstudio
  permissionClaims:
    - group: ""
      resource: "secrets"
      state: Accepted