apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: has-binding
spec:
  reference:
    workspace:
      path: ${KCP_WORKSPACE}
      exportName: application-api
  acceptedPermissionClaims:
      - group: ""
        resource: "secrets"
      - group: ""
        resource: "configmaps"